### ISSUE TITLE
投稿後台優化功能

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#309]
* [x] DashBoard 的 table list 增加一個`如何投稿`連結到 `speaking/talk/` #313
* [x] 提醒投稿者尚未完成的數量：投稿 talk 若有尚未完成填寫 (沒有打*但尚未填寫) 的提案，提案 Tab 旁邊加上如 bootstrap 的 Badges，提醒尚未完成數量。 #314
* [x] 欄位有 “摘要、演講目標、詳細說明、大綱、補充資料” 有 model 的按鈕在欄位下說明（點選會跳出教學，可以放好得示範和不好示範，或是只放範例）。 #316 
* [x] 投稿頁面如果使用者跳出時要提示資料會遺失的警告。 ~#317~ #325
* [ ] 有 markdown 簡單教學連結（新開視窗，[範例](https://kingofamani.gitbooks.io/git-teach/content/chapter_6_gitbook/markdown.html)） #318
* [x] 在滑動的時候能夠顯示他滑到那裡，還有哪些東西沒填寫。目前沒找到類似 sample 大概是在滑動時可以顯示一個半透明的 status bar 知道他寫到哪個欄位。[範例](https://www.thenewslens.com/article/59418)。 #329 
* [x] 時間改成 30/45。 #319 

[詳細可參考](https://docs.google.com/document/d/15a_4fo0Pzrcgw89MFJV0Tc3XiwqKsRSs0xDyJd48DKU/edit)

**Comment by uranusjr** [comment]
感謝整理～～有人想認領的話可以直接喊個聲，我另外開個 issue assign 給你。

看起來 2. 3. 5. 應該主要就是套一些 Bootstrap 的東西，加上一點 template 邏輯。3. 會需要麻煩議程組提供一些文稿，5. 可能有更好的連結，歡迎建議。6. 感覺就比較難。7. 很簡單，不過為了未來擴充性可能還是得做成 setting，這部分要比較多 Python 和 Django 知識。

我後來覺得 4. 可以做得更好一點。與其警告使用者還沒存檔，不如用 [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) 直接把使用者還沒 submit 的輸入存下來。這個我先做做看好了。
