### ISSUE TITLE
CfP 還需要跟設計師討論的東西

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#63]
待修改：
- [x] Navbar #79 (include RWD version #42 ) 
- [x] Button hover and Sidebar hover #66 
- [x] 語言列選項 #42 
- [x] Edit button + Withdraw/Reactivate #80 
- [x] Manage Speakers 流程和設計（先隱藏）
- [x] Speaking pages: cfp、talk、tutorial。 #84 
- [x] 404.html, 500.html #23 
- [x] 顯示 Message #68 

針對 CfP @ccwang002 @uranusjr @starwilly 還有什麼要跟設計師討論的嗎？

**Comment by uranusjr** [comment]
不確定這個算不算設計的一部份，但目前修改 proposal 的頁面在最上面會顯示 proposal 題目，但下面又有修改的格子。應該只有一個就好，或許直接可以在標題那邊修改（類似 GitHub issue 的狀況），或者 page title（不是 head 裡面的那個）改成 “Edit Your Talk Proposal”（或 Tutorial）會比較好。

**Comment by flywindy** [comment]
我覺得可以直接改成後者，我傾向 Title 都是顯示固定的，畢竟現在的設計不能換行，所以標題兩行的話會跑掉。

**Comment by ccc-larc** [comment]
- [ ] 需要一張圖片，給 Facebook 分享用 (尺寸：1200 x 630)

**Comment by uranusjr** [comment]
現在還來得及追加嗎 XD

覺得 dashboard 的 proposal 標題應該要可以直接點，而不是需要去右邊按 Edit。當然那個按鈕可以留著，因為不是每個人都想得到可以按標題。但標題可以按好像也不會有什麼損失。

**Comment by flywindy** [comment]
@uranusjr 他今天會給我新設計，我可以順便跟他討論。

**Comment by flywindy** [comment]
跟設計師討論過後的幾項建議與討論：
- Navbar 合理要放一個 Sign In，但這功能又是只給投稿用的，所以字可能會改成`投稿`（但英文要用什麼？），會用顏色跟其他區分。
- 他覺得 Withdraw 不直覺，問說能不能換成 Delete
- 在跟設計師和 @daikeren 討論過後，暫時不上 Manage Speaker 的功能（覺得流程不順）
- 另外他也說 `Edit` 按鈕可以留著，我會再加上可以按標題的功能。

**Comment by uranusjr** [comment]
1. 還是右上角顯示 dashboard 的連結（叫做例如**講者控制台**之類的），然後按下去就是進 dashboard？如果沒登入的話反正就是導到登入頁，這樣就不用放什麼 sign in 了。

    未登入：講者控制台（導到登入頁）；已登入：講者控制台、登出。

2. 這個是針對 withdraw 還是中文（現在是翻撤回嗎）？因為 withdraw 在英文其實是很普通的用詞，應該不直覺有點怪（好像應該要讓英文母語的人來判斷會比較準）。

後兩個沒意見，我之後再把 speaker 管理的 URL 先拿掉。

**Comment by flywindy** [comment]
1. 嗯，我也是這樣想的。英文叫什麼好呢？`Dashboard` 會不會不夠明顯？呼叫 @ccwang002 
2. 英文，不過 @daikeren 說論文確實是用這個字，所以不用改也可以。只是設計師的提問我就註記在這邊。
3. Manage Speaker 的功能，至少不急著一起上線（聽 @daikeren 說頂多一兩個），所以我覺得可以開會討論一次整體流程在做。

**Comment by ccwang002** [comment]
1. Dashboard 字應該沒問題。之後 reviewer / sponsor 不是也要加進來嗎？
    我覺得就叫 dashboard 就好，網站也沒多少地方能點，應該不會複雜。
2. 我想設計師應該是覺得投稿刪不掉這件事有點怪。我覺得兩者都可以，withdraw 只要看得出來那個投稿失效了就好。例如極端一點，[用條紋把整行 proposal 蓋掉](https://css-tricks.com/stripes-css/)。
3. 多講者的機會真的很少，一年不超過 5 個吧，可以再想一想怎麼做。

**Comment by uranusjr** [comment]
對耶，我沒想到 review 和 sponsor 也要用。不然就先用 dashboard 吧，找不到的人應該會去看 `speaking/talk` 之類的頁面，可以在那邊加個投稿連結。

第二個我本來有想做個 filter 讓使用者可以選（類似 Django admin 的 sidebar 那樣），但後來就… 懶了。現在的設計是如果取消會自動被排在最後面，應該做個 `opacity: 0.25` 之類的就很明顯了？

**Comment by flywindy** [comment]
說真的，`Withdraw` 的 case 聽說也不是很多，感覺我們都花時間在討論很不常用的功能 :P
要怎麼顯示 `Withdraw` 的 proposal 我會再跟設計師討論，包含 @ccwang002 的建議，但還是以設計師為主喔？

**Comment by ccwang002** [comment]
對啊，我覺得 navbar 都比這些重要 xd 之前的投稿都沒問題，我不覺得今年會有什麼奇怪的狀況

**Comment by uranusjr** [comment]
反正這種東西就是想到就講講，真的需要的時候才能做，大家自己把先後順序調整好就好了。Nav bar 也已經決定了嘛，目前也沒其他需要討論的（應該吧？）

其實去年我就有取消過一個 proposal，方法是直接寄 email 給 Stanley。當然這不是急迫的問題，但總有一天也是要解決。

**Comment by flywindy** [comment]
`Withdraw` 我個人是覺得還算好懂啦，按下去 `Edit` 就會消失（然後 Title 那邊 link 也要記得拿掉），而且誤觸還可以取消 XD
`Manage Speaker` 太特例（去年只有一組），加上流程和限制很多，所以我覺得可以先不上。
